require File.dirname(__FILE__) + '/../init.rb'
require 'rubygems'
require 'hpricot'
require 'test/unit'
require 'spec'
require 'active_support'
require File.dirname(__FILE__) + '/spec_helpers/mechanize_mock_helper.rb'
